name: Build

on:
  push:
    branches-ignore:
      # Ignore Dependabot branches because it will also open a pull request, which would cause the
      # workflow to redundantly run twice
      - dependabot/**
  pull_request:


permissions:
  contents: read # to fetch code (actions/checkout)

env:
  # Enable colored terminal output, see https://doc.rust-lang.org/cargo/reference/config.html#termcolor
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }})

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1

      - name: Install cargo-make
        uses: taiki-e/install-action@787505cde8a44ea468a00478fe52baf23b15bccd  #v2.75.21
        with:
          tool: cargo-make@0.37.24

      - name: Build
        run: cargo make

      - name: Install cargo-hack
        uses: taiki-e/install-action@787505cde8a44ea468a00478fe52baf23b15bccd  #v2.75.21
        with:
          tool: cargo-hack@0.6.42
      # See https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version
      - name: Check 'rust-version' compatibility
        run: cargo hack check --rust-version --workspace --all-targets --all-features
